### ISSUE TITLE
Story: Detect Object  

### ISSUE THREAD

**Issue by ramzouza** [YannCedric/Simple-Camera#12]
Wiki Entry : [Detect Object](https://github.com/ramzouza/Simple-Camera/wiki/Detect-Object)

- [x] Lens can recognize object and give a notification what they are 
- [x] Lens can display information about the object which the user can close.
- [x] Passing UI Test 
- [x] Passing Unit Test

**Comment by jonthemango** [comment]
Unit Test for QR code needs to be removed since controller does nothing now that new SmartHubDialog class is added. Test doesn't actually test. 

Also need UI tests.

**Comment by jonthemango** [comment]
Added UI test last week. Added Unit Test now.
