### ISSUE TITLE
Mock-up: Detect Object 

### ISSUE THREAD

**Issue by ramzouza** [YannCedric/Simple-Camera#17]
Creation of the Mock-up for Detect Object lens.  This new Mock-up will contain a new lens button in the Smart-Hub

- [x] Creation of the Mock-up 
- [x] Upload the picture to the Wiki

**Comment by EricKokmanian** [comment]
https://github.com/ramzouza/Simple-Camera/wiki/Detect-Object

**Comment by jonthemango** [comment]
Thank you @EricKokmanian
