### ISSUE TITLE
Story: QR Code Scanner

### ISSUE THREAD

**Issue by jonthemango** [YannCedric/Simple-Camera#2]
Wiki Entry:
https://github.com/ramzouza/Simple-Camera/wiki/Bar-Code-Scanner

- [x] Include Firebase in the project build 
- [x] Lens can recognize QR codes 
- [x] A pop-up appears with the URL of the code
- [x] Passing Unit Test

**Comment by ramzouza** [comment]
![image](https://user-images.githubusercontent.com/25621431/52542621-bef72b00-2d6f-11e9-8072-82cdad45b401.png)
