### ISSUE TITLE
Story : Swipe Handler 

### ISSUE THREAD

**Issue by skanderbm123** [YannCedric/Simple-Camera#33]
Wiki Entry: [SwipeHandler for SmartHub](https://github.com/ramzouza/Simple-Camera/wiki/SwipeHandler-for-SmartHub)

- [x]  User can swipe right to access the SmartHub ( only Right swipe is accepted )
- [x]  User can swipe left on the SmartHub to return to the main Menu ( only Left swipe is accepted )
- [x] Passing UI Test

**Comment by EricKokmanian** [comment]
Added extra functionality : 
 - [x] User can now double tap the middle of screen to flip the camera (rear/front)
