### ISSUE TITLE
Story: Smart Hub

### ISSUE THREAD

**Issue by ramzouza** [YannCedric/Simple-Camera#7]
Wiki Entry:
https://github.com/ramzouza/Simple-Camera/wiki/Smart-Hub

- [x] Smart Hub button brings you to the set of lenses   
- [x] You can alternate from one lens to the other with a swipe
- [ ] Passing Unit Test

**Comment by jonthemango** [comment]
So If you launch app now there is a button which when pressed should bring you to the "Smart Hub" for now it turns on a light and flashes a message. This function should be added too to make a smart hub appear.

**Comment by EricKokmanian** [comment]
![acceptancetesting 7](https://user-images.githubusercontent.com/25437099/52539212-79c00280-2d49-11e9-863f-e1c3b6dc8791.png)

**Comment by ramzouza** [comment]
Smart Hub V1 is completed future improvement will be contained within other issues
